version: '3.7'

services:
  db:
    build:
      context: ./backend
      dockerfile: ./compose/postgres/Dockerfile
    env_file:
      - .envs

  app:
    build:
      context: ./backend
      dockerfile: ./compose/django/Dockerfile
    env_file:
      - .envs
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: ./compose/django/dev_entrypoint.sh